name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: 'cd ./tasks && deno run --allow-read --allow-write create_json.ts echo "create json!!"'
